### 24절기와 공휴일 정보를 API를 통해 가져와서 DB에 저장하기

In [3]:
import requests
from urllib.parse import quote
import pandas as pd

In [2]:
with open('keys/govDataApiKey.txt') as file:
    govdata_key = file.read()

- 공휴일 정보

In [4]:
base_holiday_url = 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?_type=json&numOfRows=50&solYear='
url = f'{base_holiday_url}2020&ServiceKey={quote(govdata_key)}'
results = requests.get(url).json()
results

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'dateKind': '01',
      'dateName': '1월1일',
      'isHoliday': 'Y',
      'locdate': 20200101,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '설날',
      'isHoliday': 'Y',
      'locdate': 20200124,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '설날',
      'isHoliday': 'Y',
      'locdate': 20200125,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '설날',
      'isHoliday': 'Y',
      'locdate': 20200126,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '설날',
      'isHoliday': 'Y',
      'locdate': 20200127,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '삼일절',
      'isHoliday': 'Y',
      'locdate': 20200301,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '제21대 국회의원선거',
      'isHoliday': 'Y',
      'locdate': 20200415,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '부처님오신날',
      'isHoliday': 'Y',
      'locdate': 20200430,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '어린이날',
      'isHoliday': 'Y',
      'locdate': 20200505,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '현충일',
      'isHoliday': 'Y',
      'locdate': 20200606,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '광복절',
      'isHoliday': 'Y',
      'locdate': 20200815,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '임시공휴일',
      'isHoliday': 'Y',
      'locdate': 20200817,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '추석',
      'isHoliday': 'Y',
      'locdate': 20200930,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '추석',
      'isHoliday': 'Y',
      'locdate': 20201001,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '추석',
      'isHoliday': 'Y',
      'locdate': 20201002,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '개천절',
      'isHoliday': 'Y',
      'locdate': 20201003,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '한글날',
      'isHoliday': 'Y',
      'locdate': 20201009,
      'seq': 1},
     {'dateKind': '01',
      'dateName': '기독탄신일',
      'isHoliday': 'Y',
      'locdate': 20201225,
      'seq': 1}]},
   'numOfRows': 50,
   'pageNo': 1,
   'totalCount': 18}}}

In [9]:
holidays_data = results['response']['body']['items']['item']
holidays_data[0]

{'dateKind': '01',
 'dateName': '1월1일',
 'isHoliday': 'Y',
 'locdate': 20200101,
 'seq': 1}

In [10]:
df = pd.DataFrame(holidays_data)
df

   dateKind     dateName isHoliday   locdate  seq
0        01         1월1일         Y  20200101    1
1        01           설날         Y  20200124    1
2        01           설날         Y  20200125    1
3        01           설날         Y  20200126    1
4        01           설날         Y  20200127    1
5        01          삼일절         Y  20200301    1
6        01  제21대 국회의원선거         Y  20200415    1
7        01       부처님오신날         Y  20200430    1
8        01         어린이날         Y  20200505    1
9        01          현충일         Y  20200606    1
10       01          광복절         Y  20200815    1
11       01        임시공휴일         Y  20200817    1
12       01           추석         Y  20200930    1
13       01           추석         Y  20201001    1
14       01           추석         Y  20201002    1
15       01          개천절         Y  20201003    1
16       01          한글날         Y  20201009    1
17       01        기독탄신일         Y  20201225    1

- 24절기 정보

In [11]:
base_24_url = 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/get24DivisionsInfo?_type=json&numOfRows=50&solYear='
url = f'{base_24_url}2020&ServiceKey={quote(govdata_key)}'
results = requests.get(url).json()
results

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'},
  'body': {'items': {'item': [{'dateKind': '03',
      'dateName': '소한',
      'isHoliday': 'N',
      'kst': '0630      ',
      'locdate': 20200106,
      'seq': 1,
      'sunLongitude': 285},
     {'dateKind': '03',
      'dateName': '대한',
      'isHoliday': 'N',
      'kst': '2355      ',
      'locdate': 20200120,
      'seq': 1,
      'sunLongitude': 300},
     {'dateKind': '03',
      'dateName': '입춘',
      'isHoliday': 'N',
      'kst': '1803      ',
      'locdate': 20200204,
      'seq': 1,
      'sunLongitude': 315},
     {'dateKind': '03',
      'dateName': '우수',
      'isHoliday': 'N',
      'kst': '1357      ',
      'locdate': 20200219,
      'seq': 1,
      'sunLongitude': 330},
     {'dateKind': '03',
      'dateName': '경칩',
      'isHoliday': 'N',
      'kst': '1157      ',
      'locdate': 20200305,
      'seq': 1,
      'sunLongitude': 345},
     {'dateKind': '03',
      'dateName': '춘분',
      'isHoliday': 'N',
      'kst': '0320      ',
      'locdate': 20200320,
      'seq': 1,
      'sunLongitude': 0},
     {'dateKind': '03',
      'dateName': '청명',
      'isHoliday': 'N',
      'kst': '1638      ',
      'locdate': 20200404,
      'seq': 1,
      'sunLongitude': 15},
     {'dateKind': '03',
      'dateName': '곡우',
      'isHoliday': 'N',
      'kst': '2345      ',
      'locdate': 20200419,
      'seq': 2,
      'sunLongitude': 30},
     {'dateKind': '03',
      'dateName': '입하',
      'isHoliday': 'N',
      'kst': '0951      ',
      'locdate': 20200505,
      'seq': 2,
      'sunLongitude': 45},
     {'dateKind': '03',
      'dateName': '소만',
      'isHoliday': 'N',
      'kst': '2249      ',
      'locdate': 20200520,
      'seq': 1,
      'sunLongitude': 60},
     {'dateKind': '03',
      'dateName': '망종',
      'isHoliday': 'N',
      'kst': '1358      ',
      'locdate': 20200605,
      'seq': 2,
      'sunLongitude': 75},
     {'dateKind': '03',
      'dateName': '하지',
      'isHoliday': 'N',
      'kst': '0644      ',
      'locdate': 20200621,
      'seq': 1,
      'sunLongitude': 90},
     {'dateKind': '03',
      'dateName': '소서',
      'isHoliday': 'N',
      'kst': '0014      ',
      'locdate': 20200707,
      'seq': 1,
      'sunLongitude': 105},
     {'dateKind': '03',
      'dateName': '대서',
      'isHoliday': 'N',
      'kst': '1737      ',
      'locdate': 20200722,
      'seq': 1,
      'sunLongitude': 120},
     {'dateKind': '03',
      'dateName': '입추',
      'isHoliday': 'N',
      'kst': '1006      ',
      'locdate': 20200807,
      'seq': 1,
      'sunLongitude': 135},
     {'dateKind': '03',
      'dateName': '처서',
      'isHoliday': 'N',
      'kst': '0045      ',
      'locdate': 20200823,
      'seq': 1,
      'sunLongitude': 150},
     {'dateKind': '03',
      'dateName': '백로',
      'isHoliday': 'N',
      'kst': '1308      ',
      'locdate': 20200907,
      'seq': 1,
      'sunLongitude': 165},
     {'dateKind': '03',
      'dateName': '추분',
      'isHoliday': 'N',
      'kst': '2231      ',
      'locdate': 20200922,
      'seq': 1,
      'sunLongitude': 180},
     {'dateKind': '03',
      'dateName': '한로',
      'isHoliday': 'N',
      'kst': '0455      ',
      'locdate': 20201008,
      'seq': 2,
      'sunLongitude': 195},
     {'dateKind': '03',
      'dateName': '상강',
      'isHoliday': 'N',
      'kst': '0800      ',
      'locdate': 20201023,
      'seq': 1,
      'sunLongitude': 210},
     {'dateKind': '03',
      'dateName': '입동',
      'isHoliday': 'N',
      'kst': '0814      ',
      'locdate': 20201107,
      'seq': 1,
      'sunLongitude': 225},
     {'dateKind': '03',
      'dateName': '소설',
      'isHoliday': 'N',
      'kst': '0540      ',
      'locdate': 20201122,
      'seq': 1,
      'sunLongitude': 240},
     {'dateKind': '03',
      'dateName': '대설',
      'isHoliday': 'N',
      'kst': '0109      ',
      'locdate': 20201207,
      'seq': 1,
      'sunLongitude': 255},
     {'dateKind': '03',
      'dateName': '동지',
      'isHoliday': 'N',
      'kst': '1902      ',
      'locdate': 20201221,
      'seq': 1,
      'sunLongitude': 270}]},
   'numOfRows': 50,
   'pageNo': 1,
   'totalCount': 24}}}

In [12]:
twentyfours_data = results['response']['body']['items']['item']
pd.DataFrame(twentyfours_data)

   dateKind dateName isHoliday         kst   locdate  seq  sunLongitude
0        03       소한         N  0630        20200106    1           285
1        03       대한         N  2355        20200120    1           300
2        03       입춘         N  1803        20200204    1           315
3        03       우수         N  1357        20200219    1           330
4        03       경칩         N  1157        20200305    1           345
5        03       춘분         N  0320        20200320    1             0
6        03       청명         N  1638        20200404    1            15
7        03       곡우         N  2345        20200419    2            30
8        03       입하         N  0951        20200505    2            45
9        03       소만         N  2249        20200520    1            60
10       03       망종         N  1358        20200605    2            75
11       03       하지         N  0644        20200621    1            90
12       03       소서         N  0014        20200707    1           105
13       03       대서         N  1737        20200722    1           120
14       03       입추         N  1006        20200807    1           135
15       03       처서         N  0045        20200823    1           150
16       03       백로         N  1308        20200907    1           165
17       03       추분         N  2231        20200922    1           180
18       03       한로         N  0455        20201008    2           195
19       03       상강         N  0800        20201023    1           210
20       03       입동         N  0814        20201107    1           225
21       03       소설         N  0540        20201122    1           240
22       03       대설         N  0109        20201207    1           255
23       03       동지         N  1902        20201221    1           270

- DB에 저장

In [13]:
import sqlite3 as sq

In [14]:
df.head()

  dateKind dateName isHoliday   locdate  seq
0       01     1월1일         Y  20200101    1
1       01       설날         Y  20200124    1
2       01       설날         Y  20200125    1
3       01       설날         Y  20200126    1
4       01       설날         Y  20200127    1

In [17]:
for i in df.index:
    params = (df.dateName[i], str(df.locdate[i]), 1, 'admin')

    conn = sq.connect('test.db')
    cur = conn.cursor()

    sql = 'insert into anniversary(aname, adate, is_holiday, uid) values (?,?,?,?)'
    cur.execute(sql, params)
    conn.commit()

    cur.close()
    conn.close()

In [20]:
anniv_list = []
for anniv in twentyfours_data:
    holiday = 1 if anniv['isHoliday'] == 'Y' else 0
    anniv_list.append((anniv['dateName'], str(anniv['locdate']), holiday, 'admin'))

In [21]:
anniv_list[:3]

[('소한', '20200106', 0, 'admin'),
 ('대한', '20200120', 0, 'admin'),
 ('입춘', '20200204', 0, 'admin')]

In [22]:
conn = sq.connect('test.db')
cur = conn.cursor()

sql = 'insert into anniversary(aname, adate, is_holiday, uid) values (?,?,?,?)'
cur.executemany(sql, anniv_list)        # params의 리스트
conn.commit()

cur.close()
conn.close()

In [23]:
def insert_anniv_many(anniv_list):
    conn = sq.connect('test.db')
    cur = conn.cursor()

    sql = 'insert into anniversary(aname, adate, is_holiday, uid) values (?,?,?,?)'
    cur.executemany(sql, anniv_list)        # params의 리스트
    conn.commit()

    cur.close()
    conn.close()

In [24]:
# 2021 ~ 2025년도 공휴일과 24절기 정보
for year in range(2021, 2026):
    for base_url in [base_holiday_url, base_24_url]:
        url = f'{base_url}{year}&ServiceKey={quote(govdata_key)}'
        results = requests.get(url).json()
        anniv_data = results['response']['body']['items']['item']
        
        anniv_list = []
        for anniv in anniv_data:
            holiday = 1 if anniv['isHoliday'] == 'Y' else 0
            anniv_list.append((anniv['dateName'], str(anniv['locdate']), holiday, 'admin'))
        
        insert_anniv_many(anniv_list)

- Anniversary DAO 사용

In [25]:
import anniversary_dao as adao

In [28]:
sdate, edate = '20230606', '20230606'
results = adao.get_anniv_list(sdate, edate, 'admin')
for row in results:
    print(row)

(137, '현충일', '20230606', 1, 'admin')
(156, '망종', '20230606', 0, 'admin')

In [29]:
results = adao.get_anniv_list('20231001', '20231009', 'admin')
for row in results:
    print(row)

(142, '임시공휴일', '20231002', 1, 'admin')
(143, '개천절', '20231003', 1, 'admin')
(144, '한글날', '20231009', 1, 'admin')
(164, '한로', '20231008', 0, 'admin')

In [30]:
for year in range(2020, 2026):
    params = ('국군의날', f'{year}1001', 0, 'admin')
    adao.insert_anniv(params)

In [31]:
results = adao.get_anniv_list('20231001', '20231009', 'admin')
for row in results:
    print(row)

(142, '임시공휴일', '20231002', 1, 'admin')
(143, '개천절', '20231003', 1, 'admin')
(144, '한글날', '20231009', 1, 'admin')
(164, '한로', '20231008', 0, 'admin')
(257, '국군의날', '20231001', 0, 'admin')